#!/usr/bin/env escript
%%! -smp enable -sname erlshell -setcookie secret -hidden


main([]) ->
    usage();
main([_]) ->
    usage();
main(NodesStr) ->
    Nodes = [list_to_atom(N) || N <- NodesStr],
    [Claimant | NewNodes ] = Nodes,

    io:format("~n===============~n Adding nodes to DC of ~p: ~p ~n===========~n", [Claimant, NewNodes]),

    ok = rpc:call(Claimant, antidote_dc_manager, add_nodes_to_dc, [NewNodes], 60000).


usage() ->
    io:format("NAME~n"),
    io:format("    add_nodes_to_dc - add new nodes to a data center of a node~n~n"),
    io:format("SYNOPSIS~n"),
    io:format("    add_nodes_to_dc NODE_OF_DC NODE [NODE...] ~n~n"),
    io:format("DESCRIPTION~n"),
    io:format("    Adds nodes to an existing DC.~n"),
    io:format("    Ensure before usage that this script can connect to all required nodes (long vs short names, Erlang cookie).~n~n"),
    io:format("    NODE_OF_DC: Erlang node name, the data center new nodes will be added to~n~n"),
    io:format("    NODE: Erlang node name~n~n"),
    io:format("EXAMPLES~n"),
    io:format("    add_nodes_to_dc antidote@dc1n1 antidote@dc1n2 antidote@dc1n3~n"),
    io:format("         Add nodes dc1n2 and dc1n3 to the existing data center dc1n1~n").

