version: '3.4'

# Specify feature configuration for all nodes at once
# See AntidoteDB documentation on how to configure these features
x-antidote-features:
  &default-features
  ANTIDOTE_TXN_CERT: "true"
  ANTIDOTE_TXN_PROT: "clocksi"
  ANTIDOTE_RECOVER_FROM_LOG: "true"
  ANTIDOTE_META_DATA_ON_START: "true"
  ANTIDOTE_SYNC_LOG: "false"
  ANTIDOTE_ENABLE_LOGGING: "true"
  ANTIDOTE_AUTO_START_READ_SERVERS: "true"


services:
  dc1n1:
    container_name: dc1n1
    image: antidotedb:local-build
    environment:
      << : *default-features
      NODE_NAME: "antidote@dc1n1"
      COOKIE: "secret"
      SHORT_NAME: "true"
    ports:
      - "8101:8087"
      - "8102:3001"

  dc2n1:
    container_name: dc2n1
    image: antidotedb:local-build
    environment:
      << : *default-features
      NODE_NAME: "antidote@dc2n1"
      COOKIE: "secret"
      SHORT_NAME: "true"
    ports:
      - "8101:8087"
      - "8202:3001"

  dc3n1:
    container_name: dc3n1
    image: antidotedb:local-build
    environment:
      << : *default-features
      NODE_NAME: "antidote@dc3n1"
      COOKIE: "secret"
      SHORT_NAME: "true"
    ports:
      - "8301:8087"
      - "8302:3001"

  link-dcs:
    image: erlang:21
    volumes:
      - .:/code
    command: '/code/connect-dcs.erl'
    depends_on:
      - dc1n1
      - dc2n1
      - dc3n1
