version: '3.4'

# Specify feature configuration for all nodes at once
# See AntidoteDB documentation on how to configure these features
x-antidote-features:
  &default-features
  RING_SIZE: "2"
  ANTIDOTE_TXN_CERT: "true"
  ANTIDOTE_TXN_PROT: "clocksi"
  ANTIDOTE_RECOVER_FROM_LOG: "true"
  ANTIDOTE_META_DATA_ON_START: "true"
  ANTIDOTE_SYNC_LOG: "false"
  ANTIDOTE_ENABLE_LOGGING: "true"
  ANTIDOTE_AUTO_START_READ_SERVERS: "true"
  COOKIE: "secret"


services:
  dc1n1:
    container_name: dc1n1
    image: antidotedb:local-build
    environment:
      << : *default-features
      NODE_NAME: "antidote@dc1n1"
    ports:
      - "8101:8087"
      - "8102:3001"

  dc2n1:
    container_name: dc2n1
    image: antidotedb:local-build
    environment:
      << : *default-features
      NODE_NAME: "antidote@dc2n1"
    ports:
      - "8201:8087"
      - "8202:3001"

  link-dcs:
    image: erlang:21
    restart: on-failure
    volumes:
      - ../connect-scripts:/code
    command: '/code/join_dcs antidote@dc1n1 antidote@dc2n1'
